micronaut:
  application:
    name: registration
  server:
    port: 8080
    cors:
      enabled: true
#  security:
#    authentication: bearer
datasources:
  default:
    url: jdbc:mysql://localhost:3306/library_micronaut?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    dialect: MYSQL
jpa:
  default:
    packages-to-scan:
      - 'registration.domain'
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: update
        show_sql: true
