micronaut:
  application:
    name: reservations
  server:
    port: 8083
    cors:
      enabled: true
---
micronaut:
  security:
    token:
      jwt:
        signatures:
          secret:
            validation:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
datasources:
  default:
    url: jdbc:mysql://localhost:3306/micronaut_reservations?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    dialect: MYSQL
jpa:
  default:
    packages-to-scan:
      - 'reservations.domain'
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: update
        show_sql: true
kafka:
  bootstrap:
    servers: localhost:9092
  producers:
    default:
      retries: 5
